import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const manifest = JSON.parse(fs.readFileSync(new URL('../../extension/manifest.json', import.meta.url), 'utf8'));
const firefoxManifest = JSON.parse(fs.readFileSync(new URL('../../extension/manifest.firefox.json', import.meta.url), 'utf8'));
const assemblyInfo = fs.readFileSync(new URL('../../src/Properties/AssemblyInfo.cs', import.meta.url), 'utf8');
const bridgeSettings = fs.readFileSync(new URL('../../src/Bridge/BridgeSettings.cs', import.meta.url), 'utf8');
const pluginExt = fs.readFileSync(new URL('../../src/KeePassBrowserBridgeExt.cs', import.meta.url), 'utf8');
const updateInfo = fs.readFileSync(new URL('../../update/versioninfo.txt', import.meta.url), 'utf8');
const releaseScript = fs.readFileSync(new URL('../../scripts/build-release.ps1', import.meta.url), 'utf8');
const releaseWorkflow = fs.readFileSync(new URL('../../.github/workflows/release.yml', import.meta.url), 'utf8');
const ciWorkflow = fs.readFileSync(new URL('../../.github/workflows/ci.yml', import.meta.url), 'utf8');
const rootReadme = fs.readFileSync(new URL('../../README.md', import.meta.url), 'utf8');
const extensionReadme = fs.readFileSync(new URL('../../extension/README.md', import.meta.url), 'utf8');
const extensionRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'extension');
const scripts = manifest.content_scripts.flatMap((entry) => entry.js || []);
const assemblyVersion = `${manifest.version}.0`;

assert.equal(scripts.includes('testingInfrastructure.js'), false, 'production manifest must not inject testingInfrastructure.js into web pages');
assert.equal(scripts.includes('quick-test.js'), false, 'production manifest must not inject quick-test.js into web pages');
assert.equal(scripts.includes('test-extension.js'), false, 'production manifest must not inject test-extension.js into web pages');
assert.equal(scripts.includes('uxEnhancements.js'), false, 'production manifest must not inject extension UX theming into web pages');
assert.equal(scripts.includes('multiPageLogin.js'), false, 'production manifest must not inject legacy page-session login flow tracking into web pages');
assert.equal(scripts.includes('multiDatabase.js'), false, 'production manifest must not inject database management helpers into web pages');
assert.equal(scripts.includes('enhancedSecurity_part1.js'), false, 'production manifest must not inject extension lock state listeners into web pages');
assert.equal(scripts.includes('enhancedSecurity_part2.js'), false, 'production manifest must not inject screenshot or clipboard helpers into web pages');
assert.equal(scripts.includes('groupOrganization.js'), false, 'production manifest must not inject popup search helpers into web pages');
assert.equal(scripts.includes('passwordQuality.js'), false, 'production manifest must not inject password quality helpers into web pages');
assert.equal(manifest.permissions.includes('notifications'), true, 'manifest should request notifications for save/update/fill feedback');
assert.equal(firefoxManifest.version, manifest.version, 'Firefox and Chrome extension manifests should use the same release version');
assert.equal(releaseScript.includes('manifest.firefox.json'), true, 'release script should package a Firefox extension with the Firefox manifest');
assert.equal(releaseScript.includes('KeePassBrowserBridge-firefox-extension-$version.zip'), true, 'release script should emit a Firefox extension zip');
assert.equal(releaseWorkflow.includes('KeePassBrowserBridge-firefox-extension-$expected.zip'), true, 'release workflow should verify the Firefox extension artifact');
assert.equal(releaseWorkflow.includes('Upload Firefox extension'), true, 'release workflow should upload the Firefox extension artifact');
assert.equal(ciWorkflow.includes('npm ci'), true, 'CI workflow should install pinned Node dependencies before running verifier tests');
assert.equal(ciWorkflow.includes('npx playwright install chromium'), true, 'CI workflow should install the Chromium browser used by E2E verification');
assert.equal(ciWorkflow.includes('.\\scripts\\verify.ps1'), true, 'CI workflow should run the same full verifier used locally');
assert.equal(releaseWorkflow.includes('npm ci'), true, 'release workflow should install pinned Node dependencies before verifier tests');
assert.equal(releaseWorkflow.includes('npx playwright install chromium'), true, 'release workflow should install the Chromium browser used by E2E verification');
assert.equal(releaseWorkflow.includes('.\\scripts\\verify.ps1'), true, 'release workflow should run the same full verifier before packaging');
assert.equal(assemblyInfo.includes(`[assembly: AssemblyVersion("${assemblyVersion}")]`), true, 'plugin AssemblyVersion should match extension release version');
assert.equal(assemblyInfo.includes(`[assembly: AssemblyFileVersion("${assemblyVersion}")]`), true, 'plugin AssemblyFileVersion should match extension release version');
assert.equal(pluginExt.includes('public override string UpdateUrl'), true, 'plugin should expose a KeePass update URL');
assert.equal(bridgeSettings.includes('https://raw.githubusercontent.com/hieuck/KeePassBrowserBridge/main/update/versioninfo.txt'), true, 'plugin update URL should point to the public version info file');
assert.equal(updateInfo.replace(/\r\n/g, '\n'), `:\nKeePass Browser Bridge:${manifest.version}\n:\n`, 'KeePass update info should use the plugin title and current version');
assert.equal(releaseScript.includes('versioninfo.txt'), true, 'release script should emit the KeePass update info artifact');
assert.equal(rootReadme.includes(`Version ${manifest.version}`), true, 'root README should document the current release version');
assert.equal(rootReadme.includes('MVP development is in progress'), false, 'root README should not describe the product as the old MVP status');
assert.equal(rootReadme.includes('Chrome/Firefox extension'), true, 'root README should describe both packaged browser extension targets');
assert.equal(extensionReadme.includes(`Version ${manifest.version}`), true, 'extension README should document the current extension version');
assert.equal(extensionReadme.includes('0.2.0'), false, 'extension README should not describe an obsolete release version');
assert.equal(extensionReadme.includes('contentScript.js - Main filling logic (unchanged)'), false, 'extension README should not claim current filling logic is unchanged from an older phase');
for (const size of ['16', '48', '128']) {
  assert.equal(typeof manifest.icons?.[size], 'string', `manifest should declare ${size}px extension icon`);
  assert.equal(fs.existsSync(path.join(extensionRoot, manifest.icons[size])), true, `${size}px extension icon should exist`);
  assert.equal(typeof manifest.action?.default_icon?.[size], 'string', `action should declare ${size}px toolbar icon`);
  assert.equal(fs.existsSync(path.join(extensionRoot, manifest.action.default_icon[size])), true, `${size}px toolbar icon should exist`);
}

console.log('Manifest tests passed.');
