import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const manifest = JSON.parse(fs.readFileSync(new URL('../../extension/manifest.json', import.meta.url), 'utf8'));
const firefoxManifest = JSON.parse(fs.readFileSync(new URL('../../extension/manifest.firefox.json', import.meta.url), 'utf8'));
const packageJson = JSON.parse(fs.readFileSync(new URL('../../package.json', import.meta.url), 'utf8'));
const assemblyInfo = fs.readFileSync(new URL('../../src/Properties/AssemblyInfo.cs', import.meta.url), 'utf8');
const pluginProject = fs.readFileSync(new URL('../../src/KeePassBrowserBridge.csproj', import.meta.url), 'utf8');
const bridgeTestProject = fs.readFileSync(new URL('../../tests/KeePassBrowserBridge.Tests.csproj', import.meta.url), 'utf8');
const bridgeSettings = fs.readFileSync(new URL('../../src/Bridge/BridgeSettings.cs', import.meta.url), 'utf8');
const bridgeMethodPolicy = fs.readFileSync(new URL('../../src/Bridge/BridgeMethodPolicy.cs', import.meta.url), 'utf8');
const protocolModels = fs.readFileSync(new URL('../../src/Bridge/ProtocolModels.cs', import.meta.url), 'utf8');
const bridgeRequestHandler = fs.readFileSync(new URL('../../src/Bridge/BridgeRequestHandler.cs', import.meta.url), 'utf8');
const trustedClientStore = fs.readFileSync(new URL('../../src/Bridge/TrustedClientStore.cs', import.meta.url), 'utf8');
const updateCheckerSource = fs.readFileSync(new URL('../../src/Bridge/UpdateChecker.cs', import.meta.url), 'utf8');
const passkeyServiceSource = fs.readFileSync(new URL('../../src/Bridge/PasskeyService.cs', import.meta.url), 'utf8');
const pluginExt = fs.readFileSync(new URL('../../src/KeePassBrowserBridgeExt.cs', import.meta.url), 'utf8');
const backgroundSource = fs.readFileSync(new URL('../../extension/background.js', import.meta.url), 'utf8');
const passkeysProxyExperiment = fs.readFileSync(new URL('../../extension/passkeysProxyExperiment.js', import.meta.url), 'utf8');
const popupSource = fs.readFileSync(new URL('../../extension/popup.js', import.meta.url), 'utf8');
const optionsSource = fs.readFileSync(new URL('../../extension/options.js', import.meta.url), 'utf8');
const updateInfo = fs.readFileSync(new URL('../../update/versioninfo.txt', import.meta.url), 'utf8');
const releaseScript = fs.readFileSync(new URL('../../scripts/build-release.ps1', import.meta.url), 'utf8');
const installScript = fs.readFileSync(new URL('../../scripts/install-plugin.ps1', import.meta.url), 'utf8');
const artifactVerifyScript = fs.readFileSync(new URL('../../scripts/verify-release-artifacts.ps1', import.meta.url), 'utf8');
const verifierScript = fs.readFileSync(new URL('../../scripts/verify.ps1', import.meta.url), 'utf8');
const signedReleaseSmokeScript = fs.readFileSync(new URL('../../scripts/verify-signed-release-smoke.ps1', import.meta.url), 'utf8');
const cleanSourceSmokeScript = fs.readFileSync(new URL('../../scripts/verify-clean-source-smoke.ps1', import.meta.url), 'utf8');
const realSiteMatrixScript = fs.readFileSync(new URL('../../scripts/verify-real-site-matrix.mjs', import.meta.url), 'utf8');
const securityThreatModelScript = fs.readFileSync(new URL('../../scripts/verify-security-threat-model.mjs', import.meta.url), 'utf8');
const storeScreenshotsVerifyScript = fs.readFileSync(new URL('../../scripts/verify-store-screenshots.mjs', import.meta.url), 'utf8');
const screenshotScript = fs.readFileSync(new URL('../../scripts/capture-store-screenshots.mjs', import.meta.url), 'utf8');
const screenshotWrapper = fs.readFileSync(new URL('../../scripts/capture-store-screenshots.ps1', import.meta.url), 'utf8');
const releaseWorkflow = fs.readFileSync(new URL('../../.github/workflows/release.yml', import.meta.url), 'utf8');
const ciWorkflow = fs.readFileSync(new URL('../../.github/workflows/ci.yml', import.meta.url), 'utf8');
const rootReadme = fs.readFileSync(new URL('../../README.md', import.meta.url), 'utf8');
const extensionReadme = fs.readFileSync(new URL('../../extension/README.md', import.meta.url), 'utf8');
const extensionTestingGuide = fs.readFileSync(new URL('../../extension/TESTING_GUIDE.md', import.meta.url), 'utf8');
const realSiteValidation = fs.readFileSync(new URL('../../docs/real-site-validation.md', import.meta.url), 'utf8');
const architecture = fs.readFileSync(new URL('../../docs/architecture.md', import.meta.url), 'utf8');
const releaseReadiness = fs.readFileSync(new URL('../../docs/release-readiness.md', import.meta.url), 'utf8');
const manualSmokeEvidence = fs.readFileSync(new URL('../../docs/manual-smoke-evidence.md', import.meta.url), 'utf8');
const securityThreatModel = fs.readFileSync(new URL('../../docs/security-threat-model.md', import.meta.url), 'utf8');
const storeSubmission = fs.readFileSync(new URL('../../docs/store-submission.md', import.meta.url), 'utf8');
const storeScreenshotsReadme = fs.readFileSync(new URL('../../docs/store-assets/screenshots/README.md', import.meta.url), 'utf8');
const migrationGuide = fs.readFileSync(new URL('../../docs/migration-guide.md', import.meta.url), 'utf8');
const passkeyDesign = fs.readFileSync(new URL('../../docs/passkeys-webauthn-design.md', import.meta.url), 'utf8');
const privacyPolicy = fs.readFileSync(new URL('../../docs/privacy-policy.md', import.meta.url), 'utf8');
const releaseIntegrity = fs.readFileSync(new URL('../../docs/release-integrity.md', import.meta.url), 'utf8');
const releaseNotesTemplate = fs.readFileSync(new URL('../../docs/release-notes-template.md', import.meta.url), 'utf8');
const extensionRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'extension');
const scripts = manifest.content_scripts.flatMap((entry) => entry.js || []);
const contentScriptEntries = manifest.content_scripts || [];
const assemblyVersion = `${manifest.version}.0`;

assert.equal(scripts.includes('testingInfrastructure.js'), false, 'production manifest must not inject testingInfrastructure.js into web pages');
assert.equal(scripts.includes('quick-test.js'), false, 'production manifest must not inject quick-test.js into web pages');
assert.equal(scripts.includes('test-extension.js'), false, 'production manifest must not inject test-extension.js into web pages');
assert.equal(scripts.includes('uxEnhancements.js'), false, 'production manifest must not inject extension UX theming into web pages');
assert.equal(scripts.includes('multiPageLogin.js'), false, 'production manifest must not inject legacy page-session login flow tracking into web pages');
assert.equal(scripts.includes('multiDatabase.js'), false, 'production manifest must not inject database management helpers into web pages');
assert.equal(scripts.includes('enhancedSecurity_part1.js'), false, 'production manifest must not inject extension lock state listeners into web pages');
assert.equal(scripts.includes('enhancedSecurity_part2.js'), false, 'production manifest must not inject screenshot or clipboard helpers into web pages');
assert.equal(scripts.includes('groupOrganization.js'), false, 'production manifest must not inject popup search helpers into web pages');
assert.equal(scripts.includes('passwordQuality.js'), false, 'production manifest must not inject password quality helpers into web pages');
assert.equal(scripts.includes('passkeysProxyExperiment.js'), false, 'production manifest must not inject passkey proxy experiment into web pages');
assert.equal(manifest.background?.service_worker === 'passkeysProxyExperiment.js', false, 'production manifest must not use passkey proxy experiment as service worker');
assert.equal(manifest.permissions.includes('notifications'), true, 'manifest should request notifications for save/update/fill feedback');
assert.equal(manifest.permissions.includes('contextMenus'), true, 'Chrome manifest should request contextMenus for field actions');
assert.equal(firefoxManifest.permissions.includes('contextMenus'), true, 'Firefox manifest should request contextMenus for field actions');
assert.equal(manifest.permissions.includes('webAuthenticationProxy'), false, 'manifest must not request WebAuthn proxy permission before browser-facing passkeys are implemented');
assert.equal(firefoxManifest.permissions.includes('webAuthenticationProxy'), false, 'Firefox manifest must not request unsupported WebAuthn proxy permission');
assert.equal(contentScriptEntries.every((entry) => entry.all_frames === true), true, 'content scripts should run in iframes for embedded login widgets');
assert.equal(contentScriptEntries.every((entry) => entry.match_about_blank === true), true, 'content scripts should run in about:blank child frames when the parent URL matches');
assert.equal(firefoxManifest.version, manifest.version, 'Firefox and Chrome extension manifests should use the same release version');
assert.equal(packageJson.version, manifest.version, 'package.json version should match extension release version');
assert.equal(packageJson.scripts.verify.includes('scripts/verify.ps1'), true, 'package.json verify script should run the main verifier');
assert.equal(packageJson.scripts.build.includes('build:release'), true, 'package.json build script should use the release packaging path');
assert.equal(packageJson.scripts['build:release'].includes('scripts/build-release.ps1'), true, 'package.json build:release should run the release packaging script');
assert.equal(packageJson.scripts['build:extension'].includes('build:release'), true, 'package.json build:extension should delegate to release packaging');
assert.equal(JSON.stringify(packageJson.scripts).includes('dist/kbb-extension.zip'), false, 'package.json scripts should not create ad hoc extension ZIPs');
assert.equal(JSON.stringify(packageJson.scripts).includes('zip -r'), false, 'package.json scripts should not zip the raw extension source tree');
assert.equal((firefoxManifest.content_scripts || []).every((entry) => entry.all_frames === true), true, 'Firefox content scripts should run in iframes for embedded login widgets');
assert.equal((firefoxManifest.content_scripts || []).every((entry) => entry.match_about_blank === true), true, 'Firefox content scripts should run in about:blank child frames when the parent URL matches');
assert.equal(releaseScript.includes('manifest.firefox.json'), true, 'release script should package a Firefox extension with the Firefox manifest');
assert.equal(releaseScript.includes('KeePassBrowserBridge-firefox-extension-$version.zip'), true, 'release script should emit a Firefox extension zip');
assert.equal(releaseWorkflow.includes('Upload Firefox extension'), true, 'release workflow should upload the Firefox extension artifact');
assert.equal(ciWorkflow.includes('npm ci'), true, 'CI workflow should install pinned Node dependencies before running verifier tests');
assert.equal(ciWorkflow.includes('npx playwright install chromium'), true, 'CI workflow should install the Chromium browser used by E2E verification');
assert.equal(ciWorkflow.includes('.\\scripts\\verify.ps1'), true, 'CI workflow should run the same full verifier used locally');
assert.equal(ciWorkflow.includes('.\\scripts\\build-release.ps1'), true, 'CI workflow should build release artifacts with the release packaging script');
assert.equal(ciWorkflow.includes('.\\scripts\\verify-release-artifacts.ps1'), true, 'CI workflow should verify release artifacts with the release artifact verifier');
assert.equal(ciWorkflow.includes('actions/upload-artifact@v4'), true, 'CI workflow should upload the verified release artifact bundle');
assert.equal(ciWorkflow.includes('Package browser extensions'), false, 'CI workflow should not use the obsolete manual extension packaging step');
assert.equal(ciWorkflow.includes('KeePassBrowserBridge-chrome-extension-ci.zip'), false, 'CI workflow should not create ad hoc CI-only extension ZIP names');
assert.equal(releaseWorkflow.includes('npm ci'), true, 'release workflow should install pinned Node dependencies before verifier tests');
assert.equal(releaseWorkflow.includes('npx playwright install chromium firefox'), true, 'release workflow should install browser engines used by release-candidate E2E verification');
assert.equal(releaseWorkflow.includes('.\\scripts\\verify.ps1'), true, 'release workflow should run the same full verifier before packaging');
assert.equal(releaseWorkflow.includes('-E2EProjects chromium,firefox'), true, 'release workflow should run Chromium and Firefox E2E verification before packaging');
assert.equal(releaseWorkflow.includes('contents: write'), true, 'release workflow should be allowed to publish GitHub Releases');
assert.equal(releaseWorkflow.includes('softprops/action-gh-release@v2'), true, 'release workflow should publish a GitHub Release for plugin auto-update');
assert.equal(releaseWorkflow.includes('verify-release-artifacts.ps1'), true, 'release workflow should verify release artifacts before publishing');
assert.equal(releaseWorkflow.includes('tag_name: v${{ inputs.version }}'), true, 'release workflow should publish semantic version tags used by the plugin updater');
assert.equal(releaseWorkflow.includes('artifacts/KeePassBrowserBridge.plgx'), true, 'release workflow should attach the PLGX asset consumed by plugin auto-update');
assert.equal(releaseWorkflow.includes('artifacts/versioninfo.txt'), true, 'release workflow should attach KeePass update metadata to the release');
assert.equal(releaseWorkflow.includes('artifacts/release-manifest.json'), true, 'release workflow should attach release manifest');
assert.equal(releaseWorkflow.includes('artifacts/SHA256SUMS.txt'), true, 'release workflow should attach release checksums');
assert.equal(releaseWorkflow.includes('sign_release'), true, 'release workflow should support opt-in artifact signing');
assert.equal(releaseWorkflow.includes('KBB_GPG_PRIVATE_KEY'), true, 'release workflow should import the configured signing key when requested');
assert.equal(releaseWorkflow.includes('-SignArtifacts'), true, 'release workflow should sign artifacts when signing is requested');
assert.equal(releaseWorkflow.includes('-RequireSignatures'), true, 'release workflow should verify signatures when signing is requested');
assert.equal(releaseWorkflow.includes('-RequireCleanSource'), true, 'release workflow should require a clean source tree before publishing release artifacts');
assert.equal(releaseWorkflow.includes('expected_gpg_fingerprint'), true, 'release workflow should accept an expected signing fingerprint');
assert.equal(releaseWorkflow.includes('-ExpectedSignerFingerprint'), true, 'release workflow should pass expected signing fingerprint to artifact verifier');
assert.equal(releaseWorkflow.includes('artifacts/*.asc'), true, 'release workflow should attach detached signatures when present');
assert.equal(assemblyInfo.includes(`[assembly: AssemblyVersion("${assemblyVersion}")]`), true, 'plugin AssemblyVersion should match extension release version');
assert.equal(assemblyInfo.includes(`[assembly: AssemblyFileVersion("${assemblyVersion}")]`), true, 'plugin AssemblyFileVersion should match extension release version');
assert.equal(assemblyInfo.includes(`[assembly: AssemblyInformationalVersion("${manifest.version}")]`), true, 'plugin informational version should match extension release version for auto-update checks');
assert.equal(bridgeSettings.includes(`PluginVersion = "${manifest.version}"`), true, 'bridge-reported plugin version should match extension release version');
assert.equal(pluginExt.includes('public override string UpdateUrl'), true, 'plugin should expose a KeePass update URL');
assert.equal(pluginExt.includes('StartAutoUpdateCheck();'), true, 'plugin should check for updates after loading');
assert.equal(pluginExt.includes('new ToolStripMenuItem("Check for Updates...")'), true, 'plugin menu should expose a manual update check');
assert.equal(pluginExt.includes('InstallUpdateAsync'), true, 'plugin should install downloaded PLGX updates');
assert.equal(pluginExt.includes('KeePassBrowserBridge.plgx'), true, 'plugin updater should install the PLGX release asset');
assert.equal(pluginExt.includes('DownloadString(info.ChecksumAssetUrl)'), true, 'plugin updater should download SHA256SUMS.txt before installing updates');
assert.equal(pluginExt.includes('UpdateChecker.VerifyFileSha256'), true, 'plugin updater should verify downloaded PLGX bytes before install');
assert.equal(pluginExt.includes('PrepareForPlgxAutoUpdate'), true, 'plugin updater should prepare the Plugins directory before installing PLGX updates');
assert.equal(pluginExt.includes('KeePassBrowserBridge-auto-update-backups'), true, 'plugin updater should back up duplicate DLL artifacts before PLGX auto-update');
assert.equal(pluginExt.includes('Auto-update installs KeePassBrowserBridge.plgx and cannot continue while the DLL artifact remains'), true, 'plugin updater should refuse to install PLGX when a duplicate DLL cannot be removed');
assert.equal(updateCheckerSource.includes('ChecksumAssetUrl'), true, 'update checker should carry the checksum asset URL');
assert.equal(updateCheckerSource.includes('SHA256SUMS.txt'), true, 'update checker should require release checksum assets');
assert.equal(updateCheckerSource.includes('GetExpectedSha256'), true, 'update checker should parse SHA256SUMS.txt');
assert.equal(updateCheckerSource.includes('VerifyFileSha256'), true, 'update checker should expose file hash verification');
assert.equal(pluginExt.includes('new ToolStripMenuItem("About...")'), true, 'plugin menu should expose an About dialog');
assert.equal(pluginExt.includes('CreateAboutDialog()'), true, 'plugin should build a KeePass-side About dialog');
assert.equal(pluginExt.includes('BridgeSettings.PluginVersion'), true, 'plugin About dialog should display plugin version');
assert.equal(pluginExt.includes('BridgeSettings.UpdateInfoUrl'), true, 'plugin About dialog should display update metadata URL');
assert.equal(pluginExt.includes('http://127.0.0.1:" + GetPort() + "/bridge'), true, 'plugin About dialog should display the active bridge endpoint');
assert.equal(pluginExt.includes('Browser: '), true, 'plugin pairing dialog should display the browser name');
assert.equal(pluginExt.includes('Extension origin: '), true, 'plugin pairing dialog should display the extension origin');
assert.equal(pluginExt.includes('Only pair if you just started this request'), true, 'plugin pairing dialog should warn users before approving a pairing code');
assert.equal(bridgeSettings.includes('https://raw.githubusercontent.com/hieuck/KeePassBrowserBridge/main/update/versioninfo.txt'), true, 'plugin update URL should point to the public version info file');
assert.equal(updateInfo.replace(/\r\n/g, '\n'), `:\nKeePass Browser Bridge:${manifest.version}\n:\n`, 'KeePass update info should use the plugin title and current version');
assert.equal(releaseScript.includes('versioninfo.txt'), true, 'release script should emit the KeePass update info artifact');
assert.equal(releaseScript.includes('$commonExtensionFiles'), true, 'release script should package extension files from an explicit production allowlist');
assert.equal(releaseScript.includes('quick-test.js'), false, 'release script should not package development test helpers');
assert.equal(releaseScript.includes('passkeysProxyExperiment.js'), false, 'release script should not package passkey proxy experiment before store review');
assert.equal(releaseScript.includes('SHA256SUMS.txt'), true, 'release script should emit checksums for release artifacts');
assert.equal(releaseScript.includes('release-manifest.json'), true, 'release script should emit structured release provenance manifest');
assert.equal(releaseScript.includes('Get-GitStatusIgnoringArtifactOutput'), true, 'release script should ignore artifact output when computing source dirty-state');
assert.equal(releaseScript.includes('"describe", "--tags", "--always"'), true, 'release script should build SourceDescribe from filtered dirty-state');
assert.equal(releaseScript.includes('"describe", "--tags", "--dirty", "--always"'), false, 'release script should not let artifact output affect git describe dirty-state');
assert.equal(releaseScript.includes('Bridge\\BridgeMethodPolicy.cs'), true, 'release script should compile centralized bridge method policy');
assert.equal(verifierScript.includes('.\\src\\Bridge\\BridgeMethodPolicy.cs'), true, 'main verifier should compile centralized bridge method policy');
assert.equal(pluginProject.includes('Bridge\\BridgeMethodPolicy.cs'), true, 'plugin project should include centralized bridge method policy');
assert.equal(bridgeTestProject.includes('BridgeMethodPolicy.cs'), true, 'bridge tests should include centralized bridge method policy');
assert.equal(releaseScript.includes('[switch] $RequireCleanSource'), true, 'release script should optionally fail release builds from a dirty source tree');
assert.equal(releaseScript.includes('Release build requires a clean source tree'), true, 'release script should explain clean-source failures');
assert.equal(releaseScript.includes('[switch] $SignArtifacts'), true, 'release script should support optional detached signature generation');
assert.equal(releaseScript.includes('Invoke-GpgDetachedSignature'), true, 'release script should create GPG detached signatures when signing is enabled');
assert.equal(artifactVerifyScript.includes('quick-test.js'), true, 'artifact verifier should reject development test helpers in extension ZIPs');
assert.equal(artifactVerifyScript.includes('passkeysProxyExperiment.js'), true, 'artifact verifier should reject non-packaged passkey proxy experiments in extension ZIPs');
assert.equal(artifactVerifyScript.includes('KeePassBrowserBridge-chrome-extension-$Version.zip'), true, 'artifact verifier should inspect Chrome extension ZIP');
assert.equal(artifactVerifyScript.includes('KeePassBrowserBridge-firefox-extension-$Version.zip'), true, 'artifact verifier should inspect Firefox extension ZIP');
assert.equal(artifactVerifyScript.includes('Firefox extension package is missing passwordQuality.js.'), true, 'artifact verifier should validate the Firefox-specific packaged script');
assert.equal(artifactVerifyScript.includes('Read-ChecksumFile'), true, 'artifact verifier should parse SHA256SUMS.txt');
assert.equal(artifactVerifyScript.includes('Assert-ReleaseManifest'), true, 'artifact verifier should validate release manifest metadata');
assert.equal(artifactVerifyScript.includes('Get-FileHash'), true, 'artifact verifier should verify release checksums');
assert.equal(artifactVerifyScript.includes('Assert-ZipEntrySet'), true, 'artifact verifier should enforce exact extension ZIP file lists');
assert.equal(artifactVerifyScript.includes('extension package file list mismatch'), true, 'artifact verifier should reject unexpected extension ZIP entries');
assert.equal(artifactVerifyScript.includes('[switch] $RequireSignatures'), true, 'artifact verifier should support requiring detached signatures');
assert.equal(artifactVerifyScript.includes('Assert-GpgSignature'), true, 'artifact verifier should verify GPG detached signatures when required');
assert.equal(artifactVerifyScript.includes('ExpectedSignerFingerprint'), true, 'artifact verifier should optionally require a specific signing fingerprint');
assert.equal(artifactVerifyScript.includes('VALIDSIG'), true, 'artifact verifier should parse GPG VALIDSIG status output for signer fingerprint checks');
assert.equal(verifierScript.includes('verify-real-site-matrix.mjs'), true, 'main verifier should check the real-site validation matrix');
assert.equal(verifierScript.includes('verify-security-threat-model.mjs'), true, 'main verifier should check security threat-model evidence');
assert.equal(securityThreatModelScript.includes('BridgeMethodPolicyCoversEveryBridgeMethod'), true, 'security verifier should check bridge method policy test coverage');
assert.equal(securityThreatModelScript.includes('LoopbackBridgeServerRejectsWebPostOriginBeforeHandling'), true, 'security verifier should check web-origin bridge rejection coverage');
assert.equal(securityThreatModelScript.includes('CredentialQueryRedactsProtectedCustomFieldValues'), true, 'security verifier should check protected custom field coverage');
assert.equal(securityThreatModelScript.includes('does not prompt to save sign-up forms'), true, 'security verifier should check false-positive save prompt coverage');
assert.equal(securityThreatModelScript.includes('Assert-ReleaseManifest'), true, 'security verifier should check release artifact verification coverage');
assert.equal(securityThreatModelScript.includes('docs/release-integrity.md'), true, 'security verifier should check release notes integrity guidance');
assert.equal(securityThreatModelScript.includes('webAuthenticationProxy'), true, 'security verifier should check WebAuthn permission gating');
assert.equal(realSiteMatrixScript.includes('docs'), true, 'real-site matrix verifier should read the validation matrix');
assert.equal(realSiteMatrixScript.includes("path.join(repoRoot, 'tests', 'fixtures')"), true, 'real-site matrix verifier should check referenced fixtures');
assert.equal(realSiteMatrixScript.includes('missing automated coverage labels'), true, 'real-site matrix verifier should check documented coverage labels');
assert.equal(verifierScript.includes('verify-store-screenshots.mjs'), true, 'main verifier should check generated store screenshots');
assert.equal(storeScreenshotsVerifyScript.includes('store-assets'), true, 'store screenshot verifier should read generated store assets');
assert.equal(storeScreenshotsVerifyScript.includes('--dir'), true, 'store screenshot verifier should support temporary screenshot output directories');
assert.equal(storeScreenshotsVerifyScript.includes('1280'), true, 'store screenshot verifier should enforce store screenshot width');
assert.equal(storeScreenshotsVerifyScript.includes('800'), true, 'store screenshot verifier should enforce store screenshot height');
assert.equal(verifierScript.includes('verify-clean-source-smoke.ps1'), true, 'main verifier should exercise clean-source release gating');
assert.equal(verifierScript.includes('verify-signed-release-smoke.ps1'), true, 'main verifier should exercise signed release mode with fake GPG');
assert.equal(cleanSourceSmokeScript.includes('-RequireCleanSource'), true, 'clean-source smoke should build with clean-source enforcement');
assert.equal(cleanSourceSmokeScript.includes('.kbb-clean-source-smoke'), true, 'clean-source smoke should create a deterministic dirty marker');
assert.equal(signedReleaseSmokeScript.includes('fake-gpg.ps1'), true, 'signed release smoke should use a fake GPG command for local deterministic checks');
assert.equal(signedReleaseSmokeScript.includes('-SignArtifacts'), true, 'signed release smoke should build signed artifacts');
assert.equal(signedReleaseSmokeScript.includes('-RequireSignatures'), true, 'signed release smoke should verify required signatures');
assert.equal(signedReleaseSmokeScript.includes('-ExpectedSignerFingerprint'), true, 'signed release smoke should exercise expected signer fingerprint verification');
assert.equal(signedReleaseSmokeScript.includes('SHA256SUMS.txt.asc'), true, 'signed release smoke should require a signature for the checksum file');
assert.equal(installScript.includes('Get-Process -Name "KeePass"'), true, 'install script should refuse to install while KeePass is running');
assert.equal(installScript.includes('KeePassBrowserBridge-installed-backups'), true, 'install script should back up existing plugin artifacts outside the Plugins directory and release artifact directory');
assert.equal(installScript.includes('KeePassBrowserBridge.plgx'), true, 'install script should know about PLGX artifacts');
assert.equal(installScript.includes('KeePassBrowserBridge.dll'), true, 'install script should know about DLL artifacts');
assert.equal(screenshotScript.includes('1280'), true, 'store screenshot script should generate 1280px-wide store screenshots');
assert.equal(screenshotScript.includes('extension/manifest.json') || screenshotScript.includes("'extension', 'manifest.json'"), true, 'store screenshot script should derive release version from the extension manifest');
assert.equal(screenshotScript.includes("version: '0.9.0'"), false, 'store screenshot script should not hardcode the extension version in About screenshots');
assert.equal(screenshotScript.includes("pluginVersion: '0.9.0'"), false, 'store screenshot script should not hardcode the plugin version in About screenshots');
assert.equal(screenshotScript.includes('01-popup-pairing.png'), true, 'store screenshot script should capture pairing workflow');
assert.equal(screenshotScript.includes('02-popup-account-picker.png'), true, 'store screenshot script should capture popup account picker');
assert.equal(screenshotScript.includes('03-inline-picker.png'), true, 'store screenshot script should capture inline picker');
assert.equal(screenshotScript.includes('04-save-login-prompt.png'), true, 'store screenshot script should capture save-login prompt');
assert.equal(screenshotScript.includes('05-settings-trusted-browsers.png'), true, 'store screenshot script should capture settings and trusted browsers');
assert.equal(screenshotScript.includes('.test'), true, 'store screenshot script should use safe fixture domains');
assert.equal(screenshotScript.includes('not-shown-in-store-screenshot'), true, 'store screenshot script should avoid real credentials');
assert.equal(screenshotScript.includes('chromium'), true, 'store screenshot script should use Playwright Chromium for repeatable captures');
assert.equal(screenshotWrapper.includes('capture-store-screenshots.mjs'), true, 'PowerShell screenshot wrapper should call the Node screenshot script');
assert.equal(rootReadme.includes(`Version ${manifest.version}`), true, 'root README should document the current release version');
assert.equal(rootReadme.includes('KeePassBrowserBridge-chrome-extension-<version>.zip'), true, 'root README should use a stable placeholder for Chrome extension artifact names');
assert.equal(rootReadme.includes('KeePassBrowserBridge-firefox-extension-<version>.zip'), true, 'root README should use a stable placeholder for Firefox extension artifact names');
assert.equal(rootReadme.includes(`KeePassBrowserBridge-chrome-extension-${manifest.version}.zip`), false, 'root README should not hardcode the current Chrome extension artifact version');
assert.equal(rootReadme.includes(`KeePassBrowserBridge-firefox-extension-${manifest.version}.zip`), false, 'root README should not hardcode the current Firefox extension artifact version');
assert.equal(rootReadme.includes(`Passkeys/WebAuthn are not supported in version ${manifest.version}`), true, 'root README should tie the unsupported passkey notice to the current release version');
assert.equal(rootReadme.includes('MVP development is in progress'), false, 'root README should not describe the product as the old MVP status');
assert.equal(rootReadme.includes('Chrome/Firefox extension'), true, 'root README should describe both packaged browser extension targets');
assert.equal(rootReadme.includes('install-plugin.ps1'), true, 'root README should document the local plugin install script');
assert.equal(rootReadme.includes('capture-store-screenshots.ps1'), true, 'root README should document store screenshot generation');
assert.equal(rootReadme.includes('docs/store-submission.md'), true, 'root README should link store submission docs');
assert.equal(rootReadme.includes('docs/migration-guide.md'), true, 'root README should link migration guidance');
assert.equal(rootReadme.includes('docs/passkeys-webauthn-design.md'), true, 'root README should link passkey/WebAuthn design');
assert.equal(rootReadme.includes('docs/privacy-policy.md'), true, 'root README should link publishable privacy policy source');
assert.equal(rootReadme.includes('docs/release-integrity.md'), true, 'root README should link release integrity guidance');
assert.equal(rootReadme.includes('docs/release-notes-template.md'), true, 'root README should link release notes template');
assert.equal(rootReadme.includes('Passkeys/WebAuthn are not supported'), true, 'root README should clearly state current passkey gap');
assert.equal(rootReadme.includes('duplicate pending WebAuthn request IDs'), true, 'root README should document passkey proxy duplicate request hardening');
assert.equal(extensionReadme.includes(`Version ${manifest.version}`), true, 'extension README should document the current extension version');
assert.equal(extensionReadme.includes('0.2.0'), false, 'extension README should not describe an obsolete release version');
assert.equal(extensionReadme.includes('contentScript.js - Main filling logic (unchanged)'), false, 'extension README should not claim current filling logic is unchanged from an older phase');
assert.equal(extensionReadme.includes('docs/release-readiness.md'), true, 'extension README should point maintainers to release readiness docs');
assert.equal(extensionReadme.includes('docs/store-submission.md'), true, 'extension README should point maintainers to store submission docs');
assert.equal(extensionReadme.includes('Passkeys/WebAuthn are not supported'), true, 'extension README should disclose the current passkey gap');
assert.equal(extensionReadme.includes('docs/passkeys-webauthn-design.md'), true, 'extension README should route passkey work to the design doc');
assert.equal(extensionTestingGuide.includes('Passkeys/WebAuthn'), true, 'extension testing guide should compare passkey support explicitly');
assert.equal(extensionTestingGuide.includes('Unsupported in 0.9.0'), true, 'extension testing guide should not imply passkey parity with KeePassXC-Browser');
assert.equal(extensionTestingGuide.includes('docs/manual-smoke-evidence.md'), true, 'extension testing guide should route manual smoke results to the evidence template');
assert.equal(extensionTestingGuide.includes('-E2EProjects chromium,firefox'), true, 'extension testing guide should require cross-browser release-candidate E2E verification');
assert.equal(extensionTestingGuide.includes('docs/store-submission.md'), true, 'extension testing guide should point to store submission checks');
assert.equal(extensionTestingGuide.includes('tests/fixtures/login-page.html'), true, 'extension testing guide should prefer local fixture testing over personal production credentials');
assert.equal(architecture.includes('Chrome-family browsers and Firefox'), true, 'architecture docs should describe current browser targets');
assert.equal(architecture.includes('logins.create or logins.update'), true, 'architecture docs should cover credential mutation flow');
assert.equal(architecture.includes('docs/passkeys-webauthn-design.md'), true, 'architecture docs should point passkey protocol work to the design doc');
assert.equal(architecture.includes('release-manifest.json'), true, 'architecture docs should list the release manifest artifact');
assert.equal(architecture.includes('-RequireSignatures'), true, 'architecture docs should document signed artifact verification');
assert.equal(architecture.includes('MVP scope'), false, 'architecture docs should not retain obsolete MVP language');
assert.equal(architecture.includes('Chrome MV3 extension'), false, 'architecture docs should not describe the extension as Chrome-only');
assert.equal(releaseReadiness.includes('Chrome Web Store'), true, 'release readiness docs should cover Chrome Web Store preparation');
assert.equal(releaseReadiness.includes('Firefox AMO'), true, 'release readiness docs should cover Firefox AMO preparation');
assert.equal(releaseReadiness.includes('Edge Add-ons'), true, 'release readiness docs should cover Edge Add-ons preparation');
assert.equal(releaseReadiness.includes('http://127.0.0.1/*'), true, 'release readiness docs should explain loopback bridge permissions');
assert.equal(releaseReadiness.includes('-E2EProjects chromium,firefox'), true, 'release readiness docs should require Chromium and Firefox release-candidate E2E verification');
assert.equal(releaseReadiness.includes('verify-release-artifacts.ps1'), true, 'release readiness docs should require artifact verification');
assert.equal(releaseReadiness.includes('capture-store-screenshots.ps1'), true, 'release readiness docs should require store screenshot generation');
assert.equal(releaseReadiness.includes('docs/store-submission.md'), true, 'release readiness docs should point to store submission docs');
assert.equal(releaseReadiness.includes('docs/manual-smoke-evidence.md'), true, 'release readiness docs should require manual smoke evidence capture');
assert.equal(releaseReadiness.includes('docs/migration-guide.md'), true, 'release readiness docs should require migration guidance review');
assert.equal(releaseReadiness.includes('docs/privacy-policy.md'), true, 'release readiness docs should require privacy policy publication');
assert.equal(releaseReadiness.includes('docs/release-integrity.md'), true, 'release readiness docs should require checksum verification guidance');
assert.equal(releaseReadiness.includes('docs/release-notes-template.md'), true, 'release readiness docs should require release notes from template');
assert.equal(releaseReadiness.includes('passkeys/WebAuthn are not supported'), true, 'release readiness docs should prevent premature passkey listing claims');
assert.equal(releaseReadiness.includes('-RequireCleanSource'), true, 'release readiness docs should require clean-source release builds');
assert.equal(releaseReadiness.includes('-SignArtifacts'), true, 'release readiness docs should document signed release builds');
assert.equal(releaseReadiness.includes('-RequireSignatures'), true, 'release readiness docs should document signed release verification');
assert.equal(releaseReadiness.includes('protected custom fields are not exposed'), true, 'release readiness docs should require protected-field negative smoke coverage');
assert.equal(releaseReadiness.includes('passkeys/WebAuthn stay unsupported'), true, 'release readiness docs should require passkey unsupported smoke coverage');
assert.equal(storeSubmission.includes('Chrome Web Store'), true, 'store submission docs should cover Chrome Web Store');
assert.equal(storeSubmission.includes('Firefox AMO'), true, 'store submission docs should cover Firefox AMO');
assert.equal(storeSubmission.includes('Edge Add-ons'), true, 'store submission docs should cover Edge Add-ons');
assert.equal(storeSubmission.includes('Single purpose'), true, 'store submission docs should include single-purpose listing metadata');
assert.equal(storeSubmission.includes('Permission Justifications'), true, 'store submission docs should include permission justifications');
assert.equal(storeSubmission.includes('Privacy Statements'), true, 'store submission docs should include privacy statements');
assert.equal(storeSubmission.includes('Reviewer Notes'), true, 'store submission docs should include reviewer notes');
assert.equal(storeSubmission.includes('http://127.0.0.1/*'), true, 'store submission docs should justify loopback host permission');
assert.equal(storeSubmission.includes('webRequestAuthProvider'), true, 'store submission docs should justify Chrome HTTP auth permission');
assert.equal(storeSubmission.includes('webRequestBlocking'), true, 'store submission docs should justify Firefox HTTP auth permission');
assert.equal(storeSubmission.includes('does not send credentials to any remote server'), true, 'store submission docs should document remote-server privacy statement');
assert.equal(storeSubmission.includes('docs/store-assets/screenshots/'), true, 'store submission docs should document generated screenshot location');
assert.equal(storeSubmission.includes('docs/privacy-policy.md'), true, 'store submission docs should point to publishable privacy policy source');
assert.equal(storeSubmission.includes('docs/manual-smoke-evidence.md'), true, 'store submission docs should require manual smoke evidence before listing');
assert.equal(storeSubmission.includes('Passkeys/WebAuthn are not supported'), true, 'store submission docs should disclose the current passkey gap');
assert.equal(manualSmokeEvidence.includes('Pairing and Revocation'), true, 'manual smoke evidence template should cover pairing and revoke behavior');
assert.equal(manualSmokeEvidence.includes('Popup and Inline Fill'), true, 'manual smoke evidence template should cover popup and inline fill behavior');
assert.equal(manualSmokeEvidence.includes('Save New Login'), true, 'manual smoke evidence template should cover save-new behavior');
assert.equal(manualSmokeEvidence.includes('Update Existing Password'), true, 'manual smoke evidence template should cover update-password behavior');
assert.equal(manualSmokeEvidence.includes('HTTP Basic Auth'), true, 'manual smoke evidence template should cover HTTP auth behavior');
assert.equal(manualSmokeEvidence.includes('Protected Fields'), true, 'manual smoke evidence template should cover protected custom-field negative checks');
assert.equal(manualSmokeEvidence.includes('Passkeys/WebAuthn Unsupported'), true, 'manual smoke evidence template should cover unsupported passkey release checks');
assert.equal(manualSmokeEvidence.includes('Chromium'), true, 'manual smoke evidence template should cover Chromium smoke results');
assert.equal(manualSmokeEvidence.includes('Firefox'), true, 'manual smoke evidence template should cover Firefox smoke results');
assert.equal(manualSmokeEvidence.includes('KeePass master keys'), true, 'manual smoke evidence template should warn against recording master keys');
assert.equal(storeScreenshotsReadme.includes('01-popup-pairing.png'), true, 'store screenshot README should list pairing screenshot output');
assert.equal(storeScreenshotsReadme.includes('05-settings-trusted-browsers.png'), true, 'store screenshot README should list settings screenshot output');
assert.equal(securityThreatModel.includes('HMAC-SHA256'), true, 'security threat model should document HMAC authentication');
assert.equal(securityThreatModel.includes('replayed request'), true, 'security threat model should document replay protection');
assert.equal(securityThreatModel.includes('chrome-extension://'), true, 'security threat model should document allowed extension origins');
assert.equal(securityThreatModel.includes('protected custom field'), true, 'security threat model should document protected custom field handling');
assert.equal(securityThreatModel.includes('pair.begin/pair.complete origin binding'), true, 'security threat model should document pairing origin binding');
assert.equal(securityThreatModel.includes('last-used timestamp'), true, 'security threat model should document trusted-browser last-used auditability');
assert.equal(securityThreatModel.includes('Content-Type: application/json'), true, 'security threat model should document bridge JSON content-type enforcement');
assert.equal(securityThreatModel.includes('256 KiB'), true, 'security threat model should document bridge request-size limit');
assert.equal(securityThreatModel.includes('docs/passkeys-webauthn-design.md'), true, 'security threat model should route passkey work through the design doc');
assert.equal(securityThreatModel.includes('docs/release-integrity.md'), true, 'security threat model should route release signing limitations through the integrity doc');
assert.equal(securityThreatModel.includes('docs/privacy-policy.md'), true, 'security threat model should require privacy policy consistency before release');
assert.equal(securityThreatModel.includes('BridgeMethodPolicy'), true, 'security threat model should document centralized bridge method policy coverage');
assert.equal(migrationGuide.includes('Kee/KeePassRPC'), true, 'migration guide should cover Kee/KeePassRPC users');
assert.equal(migrationGuide.includes('KeePassXC-Browser'), true, 'migration guide should cover KeePassXC-Browser users');
assert.equal(migrationGuide.includes('Back up the KeePass database'), true, 'migration guide should start with database backup guidance');
assert.equal(migrationGuide.includes('Pair each browser profile again'), true, 'migration guide should explain fresh pairing');
assert.equal(migrationGuide.includes('Passkeys/WebAuthn are not implemented yet'), true, 'migration guide should disclose unsupported passkeys');
assert.equal(migrationGuide.includes('Rollback'), true, 'migration guide should include rollback guidance');
assert.equal(passkeyDesign.includes('Passkeys are not implemented'), true, 'passkey design should state current unsupported status');
assert.equal(passkeyDesign.includes('webAuthenticationProxy'), true, 'passkey design should address Chrome/Edge WebAuthn proxy API');
assert.equal(passkeyDesign.includes('Protocol Additions'), true, 'passkey design should define future protocol area');
assert.equal(passkeyDesign.includes('KBB-Passkey-PrivateKey'), true, 'passkey design should define protected KeePass storage fields');
assert.equal(passkeyDesign.includes('RP ID'), true, 'passkey design should require relying-party ID validation');
assert.equal(passkeyDesign.includes('Firefox'), true, 'passkey design should explicitly handle Firefox support uncertainty');
assert.equal(passkeyServiceSource.includes('PasskeyRelyingPartyValidator'), true, 'passkey backend prototype should include RP ID validation');
assert.equal(passkeyServiceSource.includes('KBB-Passkey-PrivateKey'), true, 'passkey backend prototype should store private material in the designed field');
assert.equal(passkeyServiceSource.includes('new ProtectedString(true'), true, 'passkey backend prototype should protect private key material in KeePass strings');
assert.equal(passkeyServiceSource.includes('unsupported_user_verification'), true, 'passkey backend prototype should reject required user verification until KeePass-side verification exists');
assert.equal(passkeyServiceSource.includes('CanonicalizeUserHandle'), true, 'passkey backend prototype should reject invalid create user handles before approval');
assert.equal(passkeyServiceSource.includes('invalid_user_handle'), true, 'passkey backend prototype should expose a stable invalid user-handle error code');
assert.equal(passkeyServiceSource.includes('TryNormalizeCredentialIds'), true, 'passkey backend prototype should fail closed on invalid allowCredentials before approval');
assert.equal(passkeyServiceSource.includes('invalid_allow_credential'), true, 'passkey backend prototype should expose a stable invalid allowCredentials error code');
assert.equal(passkeyServiceSource.includes('invalid_exclude_credential'), true, 'passkey backend prototype should expose a stable invalid excludeCredentials error code');
assert.equal(passkeysProxyExperiment.includes('webAuthenticationProxy'), true, 'passkey proxy experiment should reference the Chrome WebAuthn proxy API');
assert.equal(passkeysProxyExperiment.includes('does not expose caller origin'), true, 'passkey proxy experiment should refuse requests without trusted origin context');
assert.equal(passkeysProxyExperiment.includes('resolveTrustedOrigin'), true, 'passkey proxy experiment should expose a trusted-origin resolver hook');
assert.equal(passkeysProxyExperiment.includes('createTrustedOriginResolver'), true, 'passkey proxy experiment should provide a fail-closed trusted-origin resolver helper');
assert.equal(passkeysProxyExperiment.includes('webNavigation.getFrame'), true, 'passkey proxy experiment should be able to derive trusted origins from browser frame context when available');
assert.equal(passkeysProxyExperiment.includes('context && context.origin'), true, 'passkey proxy experiment should require trusted caller origin context');
assert.equal(passkeysProxyExperiment.includes('options && options.origin'), false, 'passkey proxy experiment must not trust origin from requestDetailsJson');
assert.equal(passkeysProxyExperiment.includes('isRpIdAllowedForOrigin'), true, 'passkey proxy experiment should reject RP IDs that do not match trusted origin context');
assert.equal(passkeysProxyExperiment.includes('Passkey RP ID is not valid for the trusted caller origin'), true, 'passkey proxy experiment should fail closed before bridge calls for invalid RP IDs');
assert.equal(passkeysProxyExperiment.includes('assertUserVerificationSupported'), true, 'passkey proxy experiment should reject unsupported user verification before bridge calls');
assert.equal(passkeysProxyExperiment.includes('Passkey user verification is not supported by this build'), true, 'passkey proxy experiment should expose a WebAuthn error for required user verification');
assert.equal(passkeysProxyExperiment.includes('normalizeUserHandle'), true, 'passkey proxy experiment should reject invalid create user handles before bridge calls');
assert.equal(passkeysProxyExperiment.includes('invalidUserHandleMessage'), true, 'passkey proxy experiment should expose a WebAuthn error for invalid user handles');
assert.equal(passkeysProxyExperiment.includes('normalizeChallenge'), true, 'passkey proxy experiment should reject invalid challenges before bridge calls');
assert.equal(passkeysProxyExperiment.includes('invalidChallengeMessage'), true, 'passkey proxy experiment should expose a WebAuthn error for invalid challenges');
assert.equal(passkeysProxyExperiment.includes('normalizeExcludeCredentialIds'), true, 'passkey proxy experiment should reject invalid create excludeCredentials before bridge calls');
assert.equal(passkeysProxyExperiment.includes('invalidExcludeCredentialMessage'), true, 'passkey proxy experiment should expose a WebAuthn error for invalid excludeCredentials');
assert.equal(passkeysProxyExperiment.includes('normalizeAllowCredentialIds'), true, 'passkey proxy experiment should reject invalid get allowCredentials before bridge calls');
assert.equal(passkeysProxyExperiment.includes('invalidAllowCredentialMessage'), true, 'passkey proxy experiment should expose a WebAuthn error for invalid allowCredentials');
assert.equal(passkeysProxyExperiment.includes('assertEs256CredentialAlgorithmAllowed'), true, 'passkey proxy experiment should reject create requests that do not allow ES256');
assert.equal(passkeysProxyExperiment.includes('normalizeCredentialAlgorithms'), true, 'passkey proxy experiment should forward normalized create algorithm policy to the backend');
assert.equal(passkeysProxyExperiment.includes('Passkey ES256 public-key credential algorithm is not allowed by this request'), true, 'passkey proxy experiment should expose a WebAuthn error for unsupported create algorithms');
assert.equal(passkeysProxyExperiment.includes('assertAttestationSupported'), true, 'passkey proxy experiment should reject unsupported attestation conveyance before bridge calls');
assert.equal(passkeysProxyExperiment.includes('Passkey attestation conveyance is not supported by this build'), true, 'passkey proxy experiment should expose a WebAuthn error for unsupported attestation');
assert.equal(passkeysProxyExperiment.includes('ExcludeCredentialIds'), true, 'passkey proxy experiment should forward create excludeCredentials to the backend');
assert.equal(passkeysProxyExperiment.includes('normalizeCredentialDescriptorIds'), true, 'passkey proxy experiment should normalize credential descriptor IDs');
assert.equal(passkeysProxyExperiment.includes('normalizeTimeoutMs'), true, 'passkey proxy experiment should normalize browser timeout hints');
assert.equal(passkeysProxyExperiment.includes('TimeoutMs'), true, 'passkey proxy experiment should forward browser timeout hints to the backend');
assert.equal(passkeysProxyExperiment.includes('normalizeRequestedExtensions'), true, 'passkey proxy experiment should normalize requested WebAuthn extensions');
assert.equal(passkeysProxyExperiment.includes('normalizeClientExtensionResults'), true, 'passkey proxy experiment should normalize bridge extension results for browser responses');
assert.equal(passkeysProxyExperiment.includes('credProps'), true, 'passkey proxy experiment should handle the WebAuthn credProps extension');
assert.equal(passkeysProxyExperiment.includes('duplicatePendingRequestMessage'), true, 'passkey proxy experiment should reject duplicate pending WebAuthn request IDs');
assert.equal(passkeysProxyExperiment.includes('duplicate'), true, 'passkey proxy experiment should notify cancellation hooks when duplicate WebAuthn request IDs are rejected');
assert.equal(passkeysProxyExperiment.includes('createLifecycle'), true, 'passkey proxy experiment should model attach/detach lifecycle');
assert.equal(passkeysProxyExperiment.includes('cancelPending'), true, 'passkey proxy experiment should expose explicit pending-request cleanup for browser lock');
assert.equal(passkeysProxyExperiment.includes('onRequestCanceled'), true, 'passkey proxy experiment should track canceled WebAuthn requests');
assert.equal(passkeysProxyExperiment.includes('onIsUvpaaRequest'), true, 'passkey proxy experiment should handle UVPAA requests');
assert.equal(passkeysProxyExperiment.includes('completeIsUvpaa'), true, 'passkey proxy experiment should complete UVPAA requests explicitly');
assert.equal(passkeysProxyExperiment.includes('completeCreateSuccess'), true, 'passkey proxy experiment should serialize successful create responses');
assert.equal(passkeysProxyExperiment.includes('completeGetSuccess'), true, 'passkey proxy experiment should serialize successful get responses');
assert.equal(passkeysProxyExperiment.includes('createBridgeRequestHandlers'), true, 'passkey proxy experiment should expose bridge request handlers for backend contract testing');
assert.equal(passkeysProxyExperiment.includes('passkeys.create.begin'), true, 'passkey proxy experiment should call backend create begin method');
assert.equal(passkeysProxyExperiment.includes('passkeys.create.complete'), true, 'passkey proxy experiment should call backend create complete method');
assert.equal(passkeysProxyExperiment.includes('passkeys.get.begin'), true, 'passkey proxy experiment should call backend get begin method');
assert.equal(passkeysProxyExperiment.includes('passkeys.get.complete'), true, 'passkey proxy experiment should call backend get complete method');
assert.equal(passkeysProxyExperiment.includes('passkeys.cancel'), true, 'passkey proxy experiment should cancel backend pending sessions when browser requests are canceled');
assert.equal(passkeysProxyExperiment.includes('approveCreate'), true, 'passkey proxy experiment should expose a create approval hook');
assert.equal(passkeysProxyExperiment.includes('chooseCredential'), true, 'passkey proxy experiment should expose a get credential selection hook');
assert.equal(bridgeSettings.includes('PasskeysEnabled'), true, 'bridge settings should expose an explicit passkey feature flag');
assert.equal(bridgeSettings.includes('get { return false; }'), true, 'passkey feature flag should stay disabled until browser-facing passkeys are ready');
assert.equal(protocolModels.includes('passkeys.create.begin'), true, 'protocol models should reserve passkey create method names');
assert.equal(protocolModels.includes('passkeys.get.begin'), true, 'protocol models should reserve passkey assertion method names');
assert.equal(protocolModels.includes('passkeys.cancel'), true, 'protocol models should reserve passkey cancellation method name');
assert.equal(protocolModels.includes('public string Attestation'), true, 'protocol models should carry create attestation preference to the backend');
assert.equal(protocolModels.includes('ExcludeCredentialIds'), true, 'protocol models should carry create excludeCredentials to the backend');
assert.equal(protocolModels.includes('public long TimeoutMs'), true, 'protocol models should carry browser timeout hints to the backend');
assert.equal(protocolModels.includes('RequestedExtensions'), true, 'protocol models should carry requested WebAuthn extensions to the backend');
assert.equal(protocolModels.includes('ClientExtensionResults'), true, 'protocol models should carry WebAuthn extension results back to the proxy');
assert.equal(protocolModels.includes('SupportedMethods'), true, 'hello protocol model should advertise supported methods');
assert.equal(protocolModels.includes('BridgeFeatureInfo'), true, 'hello protocol model should advertise feature flags');
assert.equal(protocolModels.includes('public string Status'), true, 'hello feature metadata should include feature status');
assert.equal(protocolModels.includes('public string Reason'), true, 'hello feature metadata should include feature status reasons');
assert.equal(bridgeRequestHandler.includes('SupportedMethods = BridgeMethodPolicy.AllMethods()'), true, 'hello handler should return the centralized supported method list');
assert.equal(bridgeRequestHandler.includes('prototype_disabled'), true, 'hello handler should mark disabled passkeys as an explicit prototype status');
assert.equal(backgroundSource.includes('pluginSupportedMethods'), true, 'extension background should expose bridge method discovery in about metadata');
assert.equal(backgroundSource.includes('pluginPasskeysEnabled'), true, 'extension background should expose bridge passkey feature state in about metadata');
assert.equal(backgroundSource.includes('pluginFeatureDetails'), true, 'extension background should expose bridge feature status metadata');
assert.equal(backgroundSource.includes('pluginPasskeysStatus'), true, 'extension background should expose passkey feature status metadata');
assert.equal(backgroundSource.includes('clearPendingPasskeyState'), true, 'extension background lock cleanup should call optional passkey proxy cleanup hooks');
assert.equal(passkeyServiceSource.includes('PasskeyApprovalRequest'), true, 'passkey backend should model KeePass approval requests');
assert.equal(passkeyServiceSource.includes('PasskeyApprovalResult'), true, 'passkey backend should model KeePass approval decisions');
assert.equal(bridgeRequestHandler.includes('RequestPasskeyApproval'), true, 'bridge handler should require KeePass approval for passkey begin methods');
assert.equal(bridgeRequestHandler.includes('excluded_credential_exists'), true, 'bridge handler should reject create requests when excludeCredentials match existing passkeys');
assert.equal(pluginExt.includes('ShowPasskeyApprovalPrompt'), true, 'KeePass plugin should wire a passkey approval prompt');
assert.equal(pluginExt.includes('CreatePasskeyApprovalDialog'), true, 'KeePass plugin should include a passkey approval dialog prototype');
assert.equal(passkeyServiceSource.includes('ClearAll()'), true, 'passkey pending store should support database lifecycle cleanup');
assert.equal(bridgeRequestHandler.includes('ClearPendingPasskeySessions'), true, 'bridge handler should expose pending passkey cleanup for KeePass lifecycle events');
assert.equal(bridgeRequestHandler.includes('PasskeysCancel'), true, 'bridge handler should route passkey cancellation');
assert.equal(pluginExt.includes('FileClosingPre'), true, 'plugin should clear pending passkey sessions when KeePass starts closing a database');
assert.equal(pluginExt.includes('FileClosed'), true, 'plugin should clear pending passkey sessions after KeePass closes a database');
assert.equal(passkeyServiceSource.includes('NormalizePendingTimeoutMs'), true, 'passkey pending store should clamp browser timeout hints to its maximum lifetime');
assert.equal(bridgeRequestHandler.includes('CreateClientExtensionResults'), true, 'passkey bridge should return requested WebAuthn extension results');
assert.equal(bridgeRequestHandler.includes('PasskeyCredPropsExtensionResult'), true, 'passkey bridge should return credProps extension results for created credentials');
assert.equal(trustedClientStore.includes('PasskeyRead = "passkeyRead"'), true, 'trusted-client store should define passkey read permission');
assert.equal(trustedClientStore.includes('PasskeyWrite = "passkeyWrite"'), true, 'trusted-client store should define passkey write permission');
assert.equal(bridgeMethodPolicy.includes('AllMethods'), true, 'bridge method policy should enumerate all supported bridge methods');
assert.equal(bridgeMethodPolicy.includes('RequiresAuthentication'), true, 'bridge method policy should classify authentication requirements');
assert.equal(bridgeMethodPolicy.includes('RequiredPermission'), true, 'bridge method policy should classify required permissions');
assert.equal(bridgeMethodPolicy.includes('TrustedClientPermissions.PasskeyRead'), true, 'bridge method policy should require passkeyRead for passkey read methods');
assert.equal(bridgeMethodPolicy.includes('TrustedClientPermissions.PasskeyWrite'), true, 'bridge method policy should require passkeyWrite for passkey write methods');
assert.equal(bridgeRequestHandler.includes('feature_disabled'), true, 'passkey bridge methods should remain feature-disabled in this build');
assert.equal(backgroundSource.includes('clientPermissionAllowList'), true, 'extension background should gate trusted-client permission updates through a central allowlist');
assert.equal(backgroundSource.includes("allowed.push('passkeyRead', 'passkeyWrite')"), true, 'extension background should only allow passkey permission updates when bridge feature discovery enables them');
assert.equal(backgroundSource.includes('about.pluginPasskeysEnabled'), true, 'extension background passkey permission updates should depend on bridge feature discovery');
assert.equal(popupSource.includes('bridgePasskeysEnabled'), true, 'popup trusted-browser UI should gate passkey permission controls on bridge feature discovery');
assert.equal(popupSource.includes("value: 'passkeyRead'"), true, 'popup trusted-browser UI should define passkey read controls behind the feature gate');
assert.equal(optionsSource.includes('bridgePasskeysEnabled'), true, 'settings trusted-browser UI should gate passkey permission controls on bridge feature discovery');
assert.equal(optionsSource.includes("value: 'passkeyRead'"), true, 'settings trusted-browser UI should define passkey read controls behind the feature gate');
assert.equal(privacyPolicy.includes('does not collect analytics'), true, 'privacy policy should state no analytics collection');
assert.equal(privacyPolicy.includes('does not send passwords'), true, 'privacy policy should state credentials are not sent to maintainers');
assert.equal(privacyPolicy.includes('created/last-used timestamps'), true, 'privacy policy should disclose trusted-browser timestamps');
assert.equal(privacyPolicy.includes('http://127.0.0.1:<port>/bridge'), true, 'privacy policy should explain local bridge communication');
assert.equal(privacyPolicy.includes('Passkey/WebAuthn credentials'), true, 'privacy policy should disclose passkey non-collection');
assert.equal(privacyPolicy.includes('Settings export intentionally excludes pairing secrets'), true, 'privacy policy should document export minimization');
assert.equal(releaseIntegrity.includes('SHA256SUMS.txt'), true, 'release integrity docs should document checksum artifact');
assert.equal(releaseIntegrity.includes('release-manifest.json'), true, 'release integrity docs should document release manifest artifact');
assert.equal(releaseIntegrity.includes('*.asc'), true, 'release integrity docs should document detached signature artifacts');
assert.equal(releaseIntegrity.includes('dirty-state'), true, 'release integrity docs should document source dirty-state provenance');
assert.equal(releaseIntegrity.includes('-RequireCleanSource'), true, 'release integrity docs should document clean-source release gating');
assert.equal(releaseIntegrity.includes('Get-FileHash'), true, 'release integrity docs should include Windows checksum verification');
assert.equal(releaseIntegrity.includes('sha256sum -c SHA256SUMS.txt'), true, 'release integrity docs should include Unix checksum verification');
assert.equal(releaseIntegrity.includes('-SignArtifacts'), true, 'release integrity docs should document maintainer signed build mode');
assert.equal(releaseIntegrity.includes('-RequireSignatures'), true, 'release integrity docs should document signature verification mode');
assert.equal(releaseIntegrity.includes('-ExpectedSignerFingerprint'), true, 'release integrity docs should document fingerprint-pinned signature verification');
assert.equal(releaseIntegrity.includes('Do not claim a release is signed'), true, 'release integrity docs should prevent premature signing claims');
assert.equal(releaseNotesTemplate.includes('docs/migration-guide.md'), true, 'release notes template should link migration guidance');
assert.equal(releaseNotesTemplate.includes('docs/passkeys-webauthn-design.md'), true, 'release notes template should disclose passkey design status');
assert.equal(releaseNotesTemplate.includes('docs/release-integrity.md'), true, 'release notes template should link checksum verification guidance');
assert.equal(releaseNotesTemplate.includes('docs/privacy-policy.md'), true, 'release notes template should link privacy policy');
assert.equal(realSiteValidation.includes('phone-login-page.html'), true, 'real-site validation matrix should track phone username/password login coverage');
assert.equal(realSiteValidation.includes('phone-username-first.html'), true, 'real-site validation matrix should track phone username-first login coverage');
assert.equal(realSiteValidation.includes('change-password-page.html'), true, 'real-site validation matrix should track change-password update coverage');
assert.equal(realSiteValidation.includes('docs/manual-smoke-evidence.md'), true, 'real-site validation docs should require manual smoke evidence capture');
assert.equal(pluginExt.includes('Last Used'), true, 'KeePass trusted-browser dialog should expose last-used timestamps');
assert.equal(screenshotScript.includes('LastUsedUtcMs'), true, 'store screenshots should fixture trusted-browser last-used timestamps');
for (const size of ['16', '48', '128']) {
  assert.equal(typeof manifest.icons?.[size], 'string', `manifest should declare ${size}px extension icon`);
  assert.equal(fs.existsSync(path.join(extensionRoot, manifest.icons[size])), true, `${size}px extension icon should exist`);
  assert.equal(typeof manifest.action?.default_icon?.[size], 'string', `action should declare ${size}px toolbar icon`);
  assert.equal(fs.existsSync(path.join(extensionRoot, manifest.action.default_icon[size])), true, `${size}px toolbar icon should exist`);
}

console.log('Manifest tests passed.');
